<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_4_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_excel('/content/drive/MyDrive/CDAC_DataBook.xlsx' ,sheet_name='ERPData')
df.head(5)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [5]:
grp1 = df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [7]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31

In [39]:
# location will become primary index
#                    v               v----------# MatrialID is the secondary index
grp1 = df.groupby(['Location', 'MaterialID'])
print(grp1.groups)

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [51]:
print(grp1.Quantity.agg('sum'))

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [41]:
new_df = grp1.agg([np.sum, np.mean , np.size])
new_df

/tmp/ipykernel_671/396776806.py:1: FutureWarning: The provided callable <function sum at 0x7c7621334860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  new_df = grp1.agg([np.sum, np.mean , np.size])
/tmp/ipykernel_671/396776806.py:1: FutureWarning: The provided callable <function mean at 0x7c7621335940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  new_df = grp1.agg([np.sum, np.mean , np.size])

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1
MWH-4    AXCP-78          36   36.000000    1
         DDBN-89          75   37.500000    2
         SDRT-67          58   58.000000    1
         TMI-43T         559   50.818182   11
MWH-5    AXCP-78         200   66.666667    3
         DDBN-89          71   71.000000    1
         GCVB-79          26   26.000000    1
         LXCV-21         174   58.000000    3
         SDRT-67         114   57.000000    2
         TMI-43T         112  112.000000    1

In [48]:
new_df.loc['MWH-1']

           Quantity
                sum        mean size
MaterialID
AXCP-78         548  109.600000    5
DDBN-89         130   43.333333    3
SDRT-67          91   45.500000    2
TMI-43T         120  120.000000    1

In [49]:
new_df.loc['MWH-1'].iloc[0]

Quantity  sum     548.0
          mean    109.6
          size      5.0
Name: AXCP-78, dtype: float64

In [50]:
new_df.loc[['MWH-1' , 'MWH-2']]

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [38]:
df1 = np.where((df.Location == 'MWH-1') & (df.MaterialID == 'AXCP-78'))
df1

df2 = df.iloc[df1[0]]
df2.sum()

MaterialID    AXCP-78AXCP-78AXCP-78AXCP-78AXCP-78
Location                MWH-1MWH-1MWH-1MWH-1MWH-1
Quantity                                      548
dtype: object

#
---

# Sorting of the DataFrame
---

In [53]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [63]:
df_sorted = df.sort_values('Quantity')

df_sorted.reset_index(drop = True)

df_sorted = df.sort_values('Quantity' , ascending = True)
df_sorted = df.sort_values('Quantity' , ascending = False) #it will print in desending order
df_sorted.tail()

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27
34    GCVB-79    MWH-5        26
16    SDRT-67    MWH-5        12
8     GCVB-79    MWH-2        10

In [ ]:
df_sort = df.sort_values([ 'Location' , "MaterialID" , 'Quantity'],
             ascending = [   True ,      False ,       True])
df_sort

In [ ]:
df_sort = df.sort_values(['Location' ,'MaterialID' ], ascending = [False , False])
df_sort.reset_index(drop = True)

#



# ***🔰Merging the DataFrame🔰***
---

In [105]:
pune = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx" ,sheet_name = 'Pune')
mumbai = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx" ,sheet_name = 'Mumbai')

In [76]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [106]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [111]:
a1 = np.where(pune.Name == 'Manoj')
print(a1)


pune.loc[a1[0] , 'Subject'] = 'Python'
pune

(array([1]),)

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj       Python     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [77]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [78]:
pd.merge(pune,mumbai)

Empty DataFrame
Columns: [Name, Subject, Grade]
Index: []

In [84]:
pd.merge(pune,mumbai , on = 'Subject') # gives subjects which are common in pune in mumbai
#                                        by Default = inner

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [112]:
pd.merge(pune,mumbai , on = 'Subject', how = 'inner')

    Name_x     Subject Grade_x   Name_y Grade_y
0   Rakesh      Python       A   Chetan       A
1    Manoj      Python       C   Chetan       A
2  Vaibhav  Statistics       B  Deepika       B
3   Hitesh  CommSkills       A    Arjun       A
4    Vinod          AI       B    Vinod       C

In [94]:
arr = np.array([-2,-3,4,5,-6,3,-3])
occ = np.where(arr<0)
occ

arr[occ[0]] = 0
arr

array([0, 0, 4, 5, 0, 3, 0])