<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_5_Pandas_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel('/content/drive/MyDrive/CDAC_DataBook.xlsx' ,sheet_name='ERPData')
df.head(5)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [6]:
x1 = np.random.randint(10,80,50)
x1

df['value'] = x1

In [7]:
df.head()

  MaterialID Location  Quantity  value
0    TMI-43T    MWH-4        34     70
1    AXCP-78    MWH-1        67     75
2    LXCV-21    MWH-2        27     64
3    AXCP-78    MWH-5        65     60
4    AXCP-78    MWH-4        36     15