<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_3_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel('/content/drive/MyDrive/CDAC_DataBook.xlsx' ,sheet_name='ERPData')
df.head(5)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [4]:
df.tail(3)

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [5]:
df.shape #Giving dimensions(rows X columns) of the table

(50, 3)

#

In [12]:
np.unique(df['MaterialID'])

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [16]:
np.unique(df.MaterialID) # df['MaterialID'] this will use for if there is space between name

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [13]:
np.unique(df['MaterialID']).reshape(-1,1)

array([['AXCP-78'],
       ['DDBN-89'],
       ['GCVB-79'],
       ['LXCV-21'],
       ['SDRT-67'],
       ['TMI-43T']], dtype=object)

In [14]:
print(np.unique(df['MaterialID']).reshape(-1,1))

[['AXCP-78']
 ['DDBN-89']
 ['GCVB-79']
 ['LXCV-21']
 ['SDRT-67']
 ['TMI-43T']]

In [17]:
len(np.unique(df.MaterialID))

6

In [20]:
print(np.unique(df.Location))
len(np.unique(df.Location))

['MWH-1' 'MWH-2' 'MWH-3' 'MWH-4' 'MWH-5']

5

In [19]:
len(np.unique(df.Quantity))

35

In [28]:
df.iloc[[2,3,4]]

  MaterialID Location  Quantity
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [29]:
df.columns.values

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [31]:
df['MaterialID'].head()

0    TMI-43T
1    AXCP-78
2    LXCV-21
3    AXCP-78
4    AXCP-78
Name: MaterialID, dtype: object

In [34]:
df.columns.values[0] = 'MaterialID'
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [58]:
ind = np.where(df.Quantity >= 70)
df1 = df.iloc[ind]
print(df1,          end='\n\n')
df1.reset_index(drop=True)

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        78
1     TMI-43T    MWH-1       120
2     TMI-43T    MWH-4        76
3     GCVB-79    MWH-2        87
4     SDRT-67    MWH-5       102
5     TMI-43T    MWH-4        75
6     DDBN-89    MWH-5        71
7     AXCP-78    MWH-1       152
8     AXCP-78    MWH-1       109
9     LXCV-21    MWH-5        83
10    TMI-43T    MWH-5       112
11    AXCP-78    MWH-5        70
12    AXCP-78    MWH-1       145
13    AXCP-78    MWH-2        85
14    AXCP-78    MWH-1        75

In [50]:
ind

(array([ 5,  9, 12, 15, 17, 21, 23, 24, 25, 27, 33, 38, 39, 46, 48]),)

In [51]:
len(ind[0])

15

In [47]:
(df.Quantity >= 70).sum()

np.int64(15)

##
#
#  
#
#
#

In [67]:
ind = np.where((df.Quantity > 70) & (df.Location == 'MWH-1'))

print(ind            ,end='\n\n')

print(df.iloc[ind]                     ,end='\n\n')

fd = df.iloc[ind]
er = fd.reset_index(drop=True)
print(er                      ,end='\n\n')

len(ind[0])

(array([ 9, 24, 25, 39, 48]),)

   MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
48    AXCP-78    MWH-1        75

  MaterialID Location  Quantity
0    TMI-43T    MWH-1       120
1    AXCP-78    MWH-1       152
2    AXCP-78    MWH-1       109
3    AXCP-78    MWH-1       145
4    AXCP-78    MWH-1        75

5

In [72]:
ind = np.where((df.Quantity >=70) | (df.Location == 'MWH-1'))

print(ind                     ,end='\n\n')

df.iloc[ind]

(array([ 1,  5,  9, 10, 12, 15, 17, 21, 23, 24, 25, 26, 27, 33, 38, 39, 40,
       41, 46, 48, 49]),)

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [81]:
ind = np.where(df.Location == 'MWH-2')

print(ind                     ,end='\n\n')

print(df.iloc[ind]                      ,end='\n\n')

df.iloc[ind]['Quantity'].sum()

(array([ 2,  7,  8, 15, 35, 36, 42, 45, 46]),)

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

np.int64(397)