<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_12_30_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

#
### 🔰Paired t test🔰

In [ ]:
before = np.array([12,14,10,9,8,13])

In [ ]:
after = np.array([11.8, 9.7, 11.3, 8.2, 7.2, 12.3])

In [ ]:
# Ho avg(before - after ) >=2
# Ho avg(before - after ) < 2 =====> Left tail test

In [ ]:
d = before - after
np.mean(d)

np.float64(0.9166666666666665)

In [ ]:
ssw.ttost_paired(before, after, low=2, upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [ ]:
scipy.stats.ttest_1samp(before - after , popmean = 2 , alternative = 'less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

#
### 🔰One Way Anova test🔰
###         ***AN***alysis ***O***f ***VA***rienace

In [ ]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

In [ ]:
df

  Col1  Col2
0    A    10
1    A    13
2    A    19
3    A    17
4    A    29
5    A    14
6    A    28
0    B    32
1    B    35
2    B    30
3    B    32
4    B    28
5    B    20
6    B    31
7    B    31
8    B    22
0    C    17
1    C    25
2    C    18
3    C    28
4    C    26
5    C    16
6    C    17
7    C    16

In [ ]:
# model creation ----> col 2 is response & col1 is factor
mod1 = ols('Col2 ~ Col1',df).fit()
#ols(ordinary least square)
# value of col2 depend on the valueof col1 or not

tbl = sm.stats.anova_lm(mod1)
print(tbl)
# last PR value is p-value
# in below output F is our test statistics.


#             df      sum_sq     mean_sq          F    PR(>F) <---------- p-value
# Col1       2.0  842.849206  421.424603  12.929323  0.000219
# Residual  21.0  684.484127   32.594482        NaN       NaN

            df      sum_sq     mean_sq          F    PR(>F)
Col1       2.0  842.849206  421.424603  12.929323  0.000219
Residual  21.0  684.484127   32.594482        NaN       NaN

In [ ]:
print(pairwise_tukeyhsd(df['Col2'], df['Col1']))

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B  14.5079 0.0002   7.2559   21.76   True
     A      C   6.5357 0.0923   -0.912 13.9834  False
     B      C  -7.9722 0.0237 -14.9647 -0.9798   True
-----------------------------------------------------


##### Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
##### group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
    grp1 grp2 meandiff p-adj   lower    upper  reject
     A      B  10.4286 0.0047   3.1074 17.7497   True
     A      C   1.8036 0.8192  -5.7151  9.3222  False
     B      C   -8.625  0.015 -15.6841 -1.5659   True
-----------------------------------------------------
the values  (0.0338 -  15.1408) are greater than zero.__| so it rejected --> True.

the values (-6.8645 - 8.6502) are between zero. _____| so it rejected --> false.

the values (-13.977 -  0.5887) are lesser than zero. ___| so it rejected --> True.

*    *p-adj* are the *p-value*

0.048 < 0.05 _ _ it will get rejected.\
0.954 > 0.05 _ _ it will get not rejected.\
0.015 < 0.05 _ _ it will get rejected.

In [64]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/data_anova.xlsx')

In [125]:
df = df.reset_index(drop =True)
df

   Col1  Col2
0     A    10
1     A    23
2     A    14
3     A    25
4     A    22
5     A    11
6     A    12
7     B    26
8     B    39
9     B    29
10    B    39
11    B    31
12    B    32
13    B    38
14    B    22
15    B    25
16    C    21
17    C    23
18    C    26
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [123]:
df.head()

  Col1  Col2
0    A    10
1    A    23
2    A    14
3    A    25
4    A    22

In [69]:
grp1 = df.groupby('Col1')

In [70]:
grp1.agg('mean')

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [88]:
samp_mean = grp1.agg('mean')
samp_mean

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [90]:
grand_mean = np.mean(df.Col2)
grand_mean

np.float64(24.333333333333332)

In [92]:
samp_mean.iloc[2]

Col2    23.25
Name: C, dtype: float64

In [96]:
7*(samp_mean.loc['A'] - grand_mean)**2 + 9*(samp_mean.loc['B'] - grand_mean)**2 + 8*(samp_mean.loc['C'] - grand_mean)**2

Col2    842.849206
dtype: float64

In [121]:
sampA = df.Col2[np.where(df.Col1=='A')[0]]
print(sampA)

sampB = df.Col2[np.where(df.Col1=='B')[0]]
print(sampB)

sampC = df.Col2[np.where(df.Col1=='C')[0]]
print(sampC)

0    10
1    23
2    14
3    25
4    22
5    11
6    12
Name: Col2, dtype: int64
7     26
8     39
9     29
10    39
11    31
12    32
13    38
14    22
15    25
Name: Col2, dtype: int64
16    21
17    23
18    26
19    19
20    29
21    27
22    17
23    24
Name: Col2, dtype: int64

In [107]:
sum((np.array(sampA) - np.array(samp_mean.loc['A']))**2) + sum((np.array(sampB) - np.array(samp_mean.loc['B']))**2) + sum((np.array(sampC) - np.array(samp_mean.loc['C']))**2)

np.float64(684.484126984127)

In [115]:
sum((np.array(df.Col2) - np.array(grand_mean))**2)

np.float64(1527.3333333333333)

In [116]:
mod1 = ols('Col2 ~ Col1',df).fit()

In [120]:
tbl = sm.stats.anova_lm(mod1)
tbl

            df      sum_sq     mean_sq          F    PR(>F)
Col1       2.0  842.849206  421.424603  12.929323  0.000219
Residual  21.0  684.484127   32.594482        NaN       NaN

## 🔰Multiple ANOVA🔰

In [126]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]

In [131]:
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
df.nunique()
df

    Resp  Factor1 Factor2
0     34        1       R
1     43        1       D
2     57        1       R
3     40        1       D
4     85        2       R
5     68        2       D
6     67        2       R
7     53        2       D
8     41        3       R
9     24        3       D
10    42        3       R
11    52        3       D

In [133]:
model = ols('Resp~Factor1+Factor2',df).fit()

In [136]:
res = sm.stats.anova_lm(model)
res

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN